server:
  port: 8083


spring:
  # config
  config:
    uri: http://127.0.0.1:8888
    discovery:
      enabled: true
      service-id: zw_config_server

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pojo.bean