server:
  port: 8083

spring:
  application:
    name: zw-provider

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zw.provider.bean

#  添加配置，配置暴露 endpoints：
management:
  endpoints:
    web:
      exposure:
        include: "*"  # include: "*" 表示暴露所有 endpoints 出去，默认是“health”，“info”