server:
  port: 8082

spring:
  application:
    name: zw-consumer

  cloud:
    config:
      name: zw-cloud #github上的配置名称，注意没有yml后缀名
      profile: dev   # 本次访问的环境配置项
      label: master   # 远程库的分支名
      uri: http://localhost:8888 #Config配置中心地址，通过它获取microservice-config-product.yml配置信息

setting:
  api:
    prefix: consumer

#  添加配置，配置暴露 endpoints：
management:
  endpoints:
    web:
      exposure:
        include: "*"  # include: "*" 表示暴露所有 endpoints 出去，默认是“health”，“info”