server:
  port: 8086

spring:
  application:
    name: zw-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-interval: 10s
        health-check-path: /actuator/health
        heartbeat:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info