server:
  port: 8081

spring:
  application:
    name: zw-base

setting:
  api:
    prefix: base

#  添加配置，配置暴露 endpoints：
management:
  endpoints:
    web:
      exposure:
        include: "*"  # include: "*" 表示暴露所有 endpoints 出去，默认是“health”，“info”