server:
  port: 8081
  servlet:
    context-path: /base
spring:
  application:
    name: base

  cloud:
    # Spring Cloud Config 访问方式
    #  / { 应用名 } / { 环境名 } [ / { 分支名 } ]
    #  / { 应用名 } - { 环境名 }.yml
    #  / { 分支名 } / { 应用名 } - { 环境名 }.yml
    #  / { 应用名 } - { 环境名 }.properties
    #  / { 分支名 } / { 应用名 } - { 环境名 }.properties\

    #  Spring Cloud Config也提供本地存储配置方式。我们只需要设置属性spring.profiles.active=native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
    #  也可以通过spring.cloud.config.server.native.searchLocations=file:F:/properties/属性来指定配置文件的位置。
    config:
      name: zw-cloud #github上的配置名称，注意没有yml后缀名
      profile: dev   # 本次访问的环境配置项
      label: master   # 远程库的分支名
      uri: http://localhost:8888 #Config配置中心地址，通过它获取microservice-config-product.yml配置信息

setting:
  api:
    prefix: base

#  添加配置，配置暴露 endpoints：
management:
  endpoints:
    web:
      exposure:
        include: "*"  # include: "*" 表示暴露所有 endpoints 出去，默认是“health”，“info”