spring:
  # 数据库链接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/spring_cloud_database?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

  cloud:
    # consul
    consul: # 必须要在 bootstrap.yml里 注入 注册中心
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-interval: 10s
        health-check-path: /actuator/health
        heartbeat:
          enabled: true

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug