spring:
  # 数据库链接
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1/spring_cloud_database?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: mysql

  cloud:
    # consul
    consul: # 必须要在 bootstrap.yml里 注入 注册中心
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        health-check-interval: 10s # 配置 Consul 健康检查频率，也就是心跳频率。
        health-check-path: /actuator/health # 配置 Consul 健康检查地址，Actuator 组件帮我们进行了实现，所以我们不需要额外的实现，地址在服务启动的时候，打印信息里面可以看到。
        heartbeat:
          enabled: true

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug