server:
  port: 8888

spring:
  application:
    name: zw-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/1131660791/zw_cloud.git
          # 搜索 uri 下面的目录
          search-paths: zw_config_content/dev